### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by charlesangus** [charlesangus/DeepC#1]
Plugins have only been built/tested on Centos Linux.

**Comment by jonassorgenfrei** [comment]
Hey @charlesangus,
i would like to help out with the Windows Site for DeepC. 
I will take a look and create a PR when i got it working.

**Comment by charlesangus** [comment]
Awesome, thanks! Looking forward to it.

**Comment by charlesangus** [comment]
I can't remember all the issues I've run into trying to get this to work, and it's been a while since I've tried, so sorry for the vagueness:

- there's a variable, I think one of the enums, that shadows some built-in variable on Windows and needs to be changed (easy enough to fix)
- I seem to recall there's something in the way the classes are structured or something that's not supported on Windows, which is a bit of a sticky wicket

Stay in touch and post any error messages you get stuck on and I'll see if I can remember anything more.

**Comment by jonassorgenfrei** [comment]
Don't worry i will just find my way trough the compiler errors :) and adjust them accordingly. 

I see thanks for the heads up :)
Yeah saw some array initializiation too which doesnt compile on windows like 
float myArray[amount]

Will go trough it this weekend to make it code wise working and in the beginning of next week i will get a nuke dev licence to test it out in nuke then :)

**Comment by jonassorgenfrei** [comment]
Got it working (the compiling step). Will test next week when i am able to run it in nuke :)

**Comment by jonassorgenfrei** [comment]
Okay finally got my nuke licence and was able to test it. 
It compiles and loads in nuke but i get access violations when running any DeepCWrapper at
DeepCWrapper.cpp line 356
return dynamic_cast<Iop*>(op) 

@charlesangus  can you tell me what the test_input function is supposed to do?

**Comment by jonassorgenfrei** [comment]
Okay seems like it is something with my settings. The examples crash too. Will investigate more into it.

**Comment by charlesangus** [comment]
The test_input function, iirc, is what determines whether the input pipe
can be attached to a given node.

**Comment by jonassorgenfrei** [comment]
Works on windows now:
https://github.com/jonassorgenfrei/DeepC

Could anyone with a linux machine give it a try to make sure i didn;t break anything there? 
@charlesangus @falkhofmann

**Comment by falkhofmann** [comment]
hey jonas,
i gave your fork a spin, build and loaded them.
seems to work fine. at least i dont see an issue inside nuke.

nevertheless I do agree on the side mask default. would better to have it turned of on default/creation.
