### ISSUE TITLE
Support for Nuke < 11.2?

### ISSUE THREAD

**Issue by dbr** [charlesangus/DeepC#22]
`DeepInPlaceOutputPlane` is used in a bunch of the nodes (Add/Remove/Shuffle), and I think this type was added in Nuke 11.2

Any thoughts on how hard it would be to support older versions of Nuke? I'm mostly asking as we are mostly still on Nuke 10.5 probably for the next few months. I think 10.5 is still being patched by Foundry, and it may be worth supporting for a while as the Nuke 10->11 upgrade is relatively difficult (given the Qt 4-> 5 transition/significant compiler changes/etc)

**Comment by charlesangus** [comment]
It's fairly easy, but performance takes a big hit. If you look back at the older releases, some of the tools were originally written for versions <11.2, so you could use that as a starting point if you wanted a <11.2 version.

The basic difference is ```DeepInPlaceOutputPlane``` allocates all the memory up front, and then you get pointers to writable samples to modify.

With the old workflow, you have to make a new ```DeepPixel``` for each spot, push_back the samples, and then add it to the ```DeepOutputPlane```.

I guess all that is a way of saying feel free to add that functionality, but I don't think I'm going to.
