### ISSUE TITLE
DeepCPMatte - Add location picker

### ISSUE THREAD

**Issue by charlesangus** [charlesangus/DeepC#4]

**Comment by falkhofmann** [comment]
since this topic came up in the office today as well, how could this look like?

plain 2d sample approach wont work due the deep samples.

first thing coming to my mind: a x/y picker in combination a z offset slider.
but TBH this doesn't feel very good as approach. 

anyone good an idea?

**Comment by falkhofmann** [comment]
so i gave it a try and it seems quite tricky.
even though a simple Color_knob picker  doesn't really do the trick ATM.
my approach is to add a color_knob and set the translate knob via knob_change callback. this does work so far.

issues:
- if I plug in the the mask in RGB and pick it from there it works, but NOT when actually looking at the Pmatte node in the viewer. so the data is not taken from the very input prior processing. only works when looking at the actual position data from the node before and pick it from there. otherwiise it picks the  data from the already processed image/created matte.
- cant get the color knob to actually use the position_data channelset. cant find the actual use case in the grade node example.

overall this seemed like an easy addition but currently i cant see a proper way without implementing the entire overhead from the Handle.cpp example

**Comment by charlesangus** [comment]
Hmmm, annoying.

Thinking laterally, what if the node was wrapped in a gizmo - then we could do something like link a Shuffle to the position_data channel, shuffle it into RGB, and attach a node to that that does the picking.

Could also/alternatively stick a Sphere node in there, and offer up interactive control in the 3d Viewer.

**Comment by charlesangus** [comment]
I think, at least for a first pass, it's fine if the picker only picks the front sample. For a lot of use cases that will be helpful. Otherwise, we would need to do something where we have a 2d picker knob on the Viewer (like the DeepSample node), see how many samples there are in that pixel, set a slider to limit to that many samples, and then check the values of the picker the user selected.
