### ISSUE TITLE
Misspelled plugin names in CMakeLists

### ISSUE THREAD

**Issue by mhamid3d** [charlesangus/DeepC#51]
The following plugins are misspelled in `src/CMakeLists.txt`, causing the build to fail.

- `DeepCMultiply` --> (`DeepCPMultiply` in CMakeLists)
- `DeepCCopyBBox` --> (`DeepCCopyBbox` in CMakeLists)

**Comment by charlesangus** [comment]
Thanks for pointing that out, I've committed but not tested a change, but this should be fixed now.
