### ISSUE TITLE
Building breaks with Nuke13.1

### ISSUE THREAD

**Issue by falkhofmann** [charlesangus/DeepC#52]
Seems like the foundry introduced a new functionality on ops called OpHints.

if trying to build and link the current source files, it throws an error and breaks. might needs fixing in the wrapper classes.
would need a solution to be compatible with old and new versions.

error below:
```
/mnt/data/Apps/nuke/Nuke13.1v1/include/DDImage/OpHints.h: In function ‘constexpr DD::Image::OpHints DD::Image::operator&(DD::Image::OpHints, DD::Image::OpHints)’:
/mnt/data/Apps/nuke/Nuke13.1v1/include/DDImage/OpHints.h:89:19: error: expected type-specifier
         using T = std::underlying_type_t <OpHints>;
         ```

**Comment by charlesangus** [comment]
Looks like this is a new thing to support the new top-down renderer. From the docs:

New virtual function on Op:

> virtual OpHints | opHints () const

May be as simple as just implementing that function and returning an OpHints, although would probably need a compiler directive to limit it to Nuke 13.1.

> 
> `enum DD::Image::OpHints | enum DD::Image::OpHints | strong`
> 
> Hints for ops so we know how to create tasks for them and how to execute them. In bottom-up mode, Nuke knows to create a cache when the engine method creates an Interest on an input. For top-down, we need to know this information when generating the task tree. 
> 
> ## Enumerator
> 
> Base flags (mutually exclusive):
> 
> - eDefault | This op uses the default rules for task creation and evaluation,  which is to wait for all inputs to be fully evaluated before starting  its own computation. Inputs will be evaluated according to the bounding  box and channels requested by connected downstream ops, so it is  important for the downstream ops to request only the data they will  actually fetch from their inputs to avoid over-rendering. For ops that  support it, the evaluation will be divided between multiple threads and  performed in parallel (currently limited to non-planar 2D Iops).
> - eChainable | This op does not need to wait for inputs to be fully evaluated before  beginning its own evaluation. When a series of eChainable ops are  connected together they will be combined into a single task "bubble" and  evaluated lazily by the bottom-up renderer. The task is considered to  be complete when the final op in the chain has been fully evaluated.  Only the results of the final op in the task will be cached for  downstream ops to use. This hint will yield the best results for ops  such as PixelIops that pass relatively small amounts of data (e.g. a  scanline) to each other and modify their input data in-place instead of  creating new outputs.
> - eIgnore | This op should not be rendered in top-down order. It will instead be  lazily evaluated in bottom-up order when downstream ops try to fetch its  output. This hint should be used for ops that cannot accurately predict  which regions and/or channels they will need to request from their  inputs until they are evaluated. The top-down system will render inputs  based on the region and/or channels requested by their connected  downstream ops. If this information is incorrect then over-rendering may  occur. The eIgnore hint can be used to avoid this problem, although  this is not guaranteed to provide a performance improvement as its use  must be balanced against the increased thread synchronisation that may  occur as a result of rendering the op lazily.
> - eIgnoreInputs | === Modifier flags (can be combined with a Base flag) ===  This op's inputs should not be rendered in top-down order. They will  instead be lazily evaluated in bottom-up order when downstream ops try  to fetch their output. This hint is intended for use alongside eIgnore  and provides a way to ignore an entire sub-graph if multiple ops are  over-rendering as a result of the op at the end of the graph being  unable to request the correct region and/or channels in top-down mode.
> - eSingleThread | This op should not be rendered with multiple scanline threads. This  hint should be used in the rare cases where multi-threading an op's  evaluation would result in a loss of performance.
> - eInternalMultithreaded | This op has internal multithreading so the top-down system should try  to avoid running it in parallel with other ops. When an op completes,  any successors with this hint will be run serially rather than in  parallel to get the maximum benefit from the op's internal  multithreading.

**Comment by falkhofmann** [comment]
this ticket is noe obsolete with the cmake refactoring from  @jonassorgenfrei 
tested just now and works flawless on nuke 13.1v1 without any modifications within the source code
- build on CentOS 7 with devtoolset-7
- verified on Mint 20

therefore closing ticket
