### ISSUE TITLE
Certain nodes not working on CentOS 7.6

### ISSUE THREAD

**Issue by charlesangus** [charlesangus/DeepC#53]
The following nodes fail with `/lib64/libm.so.6: version 'GLIBC_2.29' not found`:

- DeepCGamma
- DeepCGrade
- DeepCPMatte
- DeepCConstant

This node fails with the similar `/lib64/libm.so.6: version 'GLIBC_2.27' not found`:

- DeepCPNoise

The version of CentOS 7.6 I'm using seems to have glibc version 2.17.

@falkhofmann - what was the system the latest release was compiled on? CentOS 7? Which devtoolset version?

**Comment by falkhofmann** [comment]
ah darn

i remember having some troubles of the gcc a year ago when setting it up. also i am not entirely sure about the devtoolset.

some more information. i haven't used the cmake but the makefile itself to build

here are the specs I have set up
- OS: Linux Mint 20
- ldd (Ubuntu GLIBC 2.31-0ubuntu9.3) 2.31
- gcc (Ubuntu 4.8.5-4ubuntu8) 4.8.5
- GNU Make 4.2.1

i'll check if i can get in line with the actual specs from this repo.

**Comment by charlesangus** [comment]
Ah yeah if you're using Mint/Ubuntu 20, that's likely significantly ahead of Centos 7, which afaik is still what Nuke is built on (and probably a pretty common production distro in VFX still).

I just checked and I don't have the VM I used to build this on around anymore, but I think spinning up Centos 7.6 in a VM and using `devtoolset-7` is probably the best way to build it, and I think what I did most recently.

Foundry claims Nuke 12.2 is built on Centos 6 using devtoolset-2, which is incredibly old, and Nuke 13.1 on Centos 7.4 also using devtoolset-2. devtoolset-2 is hard to find it's so old, I seem to recall looking for it for quite a while before giving up.

**Comment by falkhofmann** [comment]
thank charles for the explanation!
i am not too deep in this entire building environment, yet. but i have looked into centos7 VM and, but as you mentioned, hard to find.

after setting up everything it seems to build.

will check the outcome during the next days on Mint again. my nuke license doesn't allow to run inside a VM.

**Comment by falkhofmann** [comment]
tested with Nuke 13.0
seemed to work.
 
one thing i would like to check prior making a new release. is there a way to cross check the binaries if they working now under CentOS as expected without actually releasing it?

the build is done on  CentOS  but due the license I only can verify under Mint. Once this "workflow" would be confirmed I'd assume the cross checking will be obsolete for upcoming releases.

**Comment by dekekincaid** [comment]
best to just follow vfxplatforms as a guide for libraries
http://vfxplatform.com/

Nuke 12.2 should be vfxplatform cy2019.  Centos 7 uses glibc 2.17.x.

**Comment by falkhofmann** [comment]
thanks deke!
sometimes the obvious is too obvious.

using Centos 7.9 with glibc 2.17 now. the built from v11.3 to v13.0  and seems working.

will check each node on each version just to make sure its proper this time.

one more thing regarding the cmake workflow. i am able to use this one now, but this "only" works for a single nuke version each time. in opposite, the plain makefile approach loops and builds all given at once. is there something i am missing as well?

again, sorry for those beginner question. (2 months ago i wasn't able to compile a node. so those steps are fairly big for myself.)

**Comment by charlesangus** [comment]
Thanks Deke, the voice of reason as usual!

As far as I know there's no reason the CMake workflow can't do all the versions at once except that it's not set up to do so. I'll make an issue for that.

**Comment by falkhofmann** [comment]
This has been addressed.
A new release were done and tagged as v0.5.5 

So far i have checked all nodes in all version if they are loading under Linux Mint 20
