### ISSUE TITLE
Create Windows Libs for the Release Package

### ISSUE THREAD

**Issue by jonassorgenfrei** [charlesangus/DeepC#72]
Will compile the DeepC Lib for Windows Nuke Versions. 
@charlesangus: What nuke versions shall i compile for?
Newest: 12 + 13?
Shall we bundle them alltogether with Linux or a Release Windows only?

**Comment by charlesangus** [comment]
11.3+ I think is good, if it's not too much trouble, 11.3 is still being used here and there.

Each version/os should be its own artifact in the release, if you look at the latest release, there's a zip for each Nuke version, we would do the same for Windows side-by-side, e.g. `DeepC-Window-Nuke11.3v6.zip` and `DeepC-Linux-Nuke11.3v6.zip`.

**Comment by jonassorgenfrei** [comment]
Allright will do.

Will try to write a script as discussed in: 
https://github.com/charlesangus/DeepC/issues/55

With the option to create the archives automatically.

**Comment by jonassorgenfrei** [comment]
Tried building all libraries, unfortunatly Nuke11.x  NDK persist of using Visual Studio 2015 which i don't have installed at the moment. 

Added the other compiles to the pre release created by @falkhofmann.
https://github.com/charlesangus/DeepC/releases/tag/untagged-40590c98ef84ab49587a

Will install VS2015 the and compile for Nuke 11.3 the next days.

**Comment by charlesangus** [comment]
If you haven't already gotten 11.3 set up, maybe it's time to dump 11. Was looking at the VFX reference platform docker images as a possible starting point for a bit more automation on the build environment setup, and they only go back to 2018, whereas Nuke 11 wants 2017, which I think is a good indication it's time to move on heh.

**Comment by jonassorgenfrei** [comment]
Yeah i havent build it yet. 
Still have it on my list to install VS2015 for it. But if you say for thenext release you want to dump 11.3 (at least on windows) let me know, then i can take it off my todolist.

**Comment by charlesangus** [comment]
Yeah, let's deprecate 11.3, simplify the build process.

c

--
416-835-0314

**Comment by jonassorgenfrei** [comment]
Sweet sounds good to me. 
Then ihave all the compiled codes already at the latest draft release from falk. 
You can add the latest linux ones and released it. I tested all the uploaded ones in the corresponding nuke builds.
