### ISSUE TITLE
Implement Deep Keymix node

### ISSUE THREAD

**Issue by falkhofmann** [charlesangus/DeepC#74]
a request we get often, is a proper keymix node for deeps. we do have a gizmo in place but this one create artifacts.

luckily the original source code from the 2d Keymix is in the nuke example files. I started with this node already but if anyone has capacity, I am happy to share (if its worth it....)

2d src code:

https://learn.foundry.com/nuke/developers/13.1/ndkreference/examples/Keymix.cpp

**Comment by falkhofmann** [comment]
[DeepCKeyMix.cpp.zip](https://github.com/charlesangus/DeepC/files/7722960/DeepCKeyMix.cpp.zip)

**Comment by charlesangus** [comment]
Idea would basically be to multiply the A samples by the mask and the B samples by the inverted mask and then it would basically be a regular DeepMerge (i.e. just concatenate the samples) I guess?

Would be useful, yeah. Idea is presumably a flat mask input.

**Comment by jonassorgenfrei** [comment]
I think it would be cool to have the option for a 3D mask as well like a primitive or so?
May be in a second node. 
Starting with simple primitives like sphere or box and may be extending it to more complex ones later?

**Comment by charlesangus** [comment]
Yeah, it's a cool thought. Makes me wonder if there's a use for an
extension of the Deep idea for "closed" sample regions, where there are
special flags for front and back samples of a "region" contained between
the two...
