### ISSUE TITLE
Video documentation

### ISSUE THREAD

**Issue by falkhofmann** [charlesangus/DeepC#76]
We should improve the wiki as stated in issue  #16 

in addition i tend to do a series of short clips. one for each node and gather them into a playlist on youtube or another platform.
by doing so we could easily extend the existing tools or update single ones in case there are new features on a single one.

@charlesangus  whats your thoughts on that?

could potentially help to reach a broader audience and serves as demo as well

**Comment by charlesangus** [comment]
Sounds great!

**Comment by falkhofmann** [comment]
as we prepare currently a new release with also the windows binaries, i think its good idea to start this one.
@jonassorgenfrei  might be able to prepare some test data which can be included in the example repo as well.

the only question is the account on which this running.
i thought about to create a new YT account with a new email which can be shared across contributors, so each person has excess to add,change or update these clips.

how does this sound?

**Comment by charlesangus** [comment]
I think that's a great idea. I might go with Vimeo, it's a lot less
cluttered/more professional looking than YouTube, but not a big deal either
way.

--
416-835-0314

**Comment by falkhofmann** [comment]
i started recording the first batch. short 1-2 minute clips so far.
will continue and gather until I would have one for each node. (or grouped by topic)
also, i st up an email, youtube and vimeo account.
once ready will upload and share the login data for all of them.

my idea is, to wrap these up, upload and publish the demos. update the DeepCExample repo with the nuke files and finally do some kind of bigger announce on some social media platforms.

**Comment by charlesangus** [comment]
Very cool, thanks Falk!

**Comment by falkhofmann** [comment]
this has been done. credenntials have been sent to contributors
