### ISSUE TITLE
DeepCPMatte needs to define front, back or average sample during pick

### ISSUE THREAD

**Issue by falkhofmann** [charlesangus/DeepC#82]
we noticed that it might be handy to define the actual sample to pick. i would argue most caused would be the sample closest to camera.

we could force it like that or having an option to define which one and setting the default to front.

any opinions on that?

**Comment by charlesangus** [comment]
It doesn't really work off of the sample position right now, but rather the
position pass value, so I'm not sure that makes sense.

Possibly relevant for DeepCWorld, though, for position pass generation?

**Comment by charlesangus** [comment]
Oh wait, you mean the colour picker, sorry.

Personally I think picking the front is probably fine in a lot of cases,
and reduces the complexity, but I'm not opposed to exposing something more.

Could possibly have an integer knob for sample number, or even a float knob
up interpolate between samples at a given x/y position?

Then you can pick anything, not just specific predetermined points.

**Comment by falkhofmann** [comment]
yeah exactly. i meant the pickers sampling.
just checked out the picker behavior since it was also requested in the office. then we noticed that if you merge multiple deeps and have  not dropped the hidden samples that the picking is off.
ATM the logic loops through all samples in an unordered way.  i spent a couple of mins to test if it would work with ordered. then using the 0 or the `pixel.sampleCount()` as index for the ordered approach. somehow it hasn't worked out.
will check during the upcoming days.

i somewhat like the idea of an integer knob to define the sample, but guess that this might be overwhelming to the user. just my guess though. my current approach was a dropdown with front and back which drives then the index of the ordered samples.
not ideal either....

**Comment by charlesangus** [comment]
The thing about the sample index knob is it only adds complexity if you use
it. If you leave it at 0, the behavior matches the 2d PMatte picker, which
is probably what people expect.

**Comment by falkhofmann** [comment]
true that.
let me fiddle around with it.

thoughts about it:
- maybe en closed Group for advanced settings. depth index defaults to 0. will need so sen an interface to judge
- we could display the amount of available samples at the pixel dynamically into some knob. the knob_changed callback is set up anyhow on the handle.
- i would expect 0 the closest sample and perhaps a convenience -1 option for the last if not want to check the sample amount and set the sample index manually. (in the NDK 0 is the furthest if i am correct.)

thanks for the feedback i might do a mockup and post it here prior continuing or merging

**Comment by charlesangus** [comment]
-1 for furthest makes sense, good idea.

Yeah I don't recall if 0 is the shallowest or deepest sample, but I think
in the UI it makes sense to present 0 as the shallowest either way.

--
416-835-0314
